[package]
name = "spike_server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[dependencies]
agent-client-protocol.workspace = true
alacritty_terminal.workspace = true
anyhow.workspace = true
futures.workspace = true
http_client = { workspace = true, features = ["github-download"] }
reqwest_client.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "process", "io-util", "io-std", "time", "macros"] }
